//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    
    public partial class capsule
    {
        public int Id { get; set; }
         [Required(ErrorMessage = "Please Enter Name !")]
        public string Name { get; set; }
         [Required(ErrorMessage = "Please Enter Company !")]
        public string company_name { get; set; }
         [Required(ErrorMessage = "Please Enter Output !")]
        public string output { get; set; }
         [Required(ErrorMessage = "Please Enter Size !")]
        public string size { get; set; }
         [Required(ErrorMessage = "Please Enter Dimension !")]
        public string dimension { get; set; }
         [Required(ErrorMessage = "Please Enter Shipping Weight !")]
        public string shipping_weight { get; set; }
         [Required(ErrorMessage = "Please Enter Power !")]
        public string Power { get; set; }
         [Required(ErrorMessage = "Please Enter Price !")]
        public string Price_ { get; set; }
         [Required(ErrorMessage = "Please Upload Image !")]
        public string pic { get; set; }
        public HttpPostedFileBase Imageupload { get; set; }
    }
}
