//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contact
    {
        public int Id { get; set; }
       
        public string Name { get; set; }
     
        public string Email { get; set; }
  
        public Nullable<int> Contact1 { get; set; }

        public string Message { get; set; }
    }
}
