//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class Liquid
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter Name !")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter Air Presuure !")]
        public string Air_pressure { get; set; }
        [Required(ErrorMessage = "Please Enter Air Volume !")]
        public string Air_volume { get; set; }
        [Required(ErrorMessage = "Please Enter Filling Speed !")]
        public string Filling_speed { get; set; }
        [Required(ErrorMessage = "Please Enter Filling Range !")]
        public string Filling_range_ { get; set; }
        [Required(ErrorMessage = "Please Enter Capacity !")]
        public string capacity_ { get; set; }
        [Required(ErrorMessage = "Please Enter Price !")]
        public string Price { get; set; }
        [Required(ErrorMessage = "Please upload image !")]
        public string img { get; set; }
        public HttpPostedFileBase Image2 { get; set; }
    }
}
