//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pharmadbEntities : DbContext
    {
        public pharmadbEntities()
            : base("name=pharmadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<capsule> capsule { get; set; }
        public virtual DbSet<Liquid> Liquid { get; set; }
        public virtual DbSet<Tablets> Tablets { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<adlogin> adlogin { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
    }
}
