//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
   
    
    public partial class Tablets
    {
        public int Id { get; set; }
          [Required(ErrorMessage = "Please Enter Name !")]
        public string Name { get; set; }
          [Required(ErrorMessage = "Please Enter Model !")]
        public Nullable<int> Model { get; set; }
          [Required(ErrorMessage = "Please Enter Dies !")]
        public string Dies { get; set; }
          [Required(ErrorMessage = "Please Enter Max Pressure !")]
        public string Max_pressure { get; set; }
         [Required(ErrorMessage = "Please Enter Max Diameter !")]
        public string Max_diameter { get; set; }
         [Required(ErrorMessage = "Please Enter Max Depth !")]
        public string Max_depth { get; set; }
         [Required(ErrorMessage = "Please Enter Production Capacity !")]
        public string Production_capacity { get; set; }
         [Required(ErrorMessage = "Please Enter Machine size !")]
        public string machine_size { get; set; }
         [Required(ErrorMessage = "Please Enter Net Weight !")]
        public string net_weight { get; set; }
         [Required(ErrorMessage = "Please Enter Power !")]
        public string power { get; set; }
         [Required(ErrorMessage = "Please Enter Max Price !")]
        public string Price_ { get; set; }
         [Required(ErrorMessage = "Please Upload Image !")]
        public string photo { get; set; }
        public HttpPostedFileBase Image3 { get; set; }
    }
}
