//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Table
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Enter Your Name !")]
        [StringLength(maximumLength: 12, MinimumLength = 3, ErrorMessage = "Username length must be Max 12 & Min 3")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter the Company !")]
        public string Comapny { get; set; }
        [Required(ErrorMessage = "Please Enter the Address !")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Enter the City !")]
        public string City { get; set; }
        [Required(ErrorMessage = "Please Enter the State !")]
        public string State { get; set; }
        [Required(ErrorMessage = "Please Enter the Postal Code !")]
        public string Postal { get; set; }
        [Required(ErrorMessage = "Please Enter the Country !")]
        public string Country { get; set; }
        [Required(ErrorMessage = "Please Enter the Email Address !")]
        public string Email { get; set; }
        [Required]
        [MaxLength(11)]
        [MinLength(1)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "must be numeric")]
        public Nullable<int> Phone { get; set; }
        [Required(ErrorMessage = "Please Enter the Comments !")]
        public string Comments { get; set; }
    }
}
